services:
  oracle-server-db:
    container_name: oracle-server-db
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: "SuperPassword"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
